apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realtime-demo-app
  template:
    metadata:
      labels:
        app: realtime-demo-app
    spec:
      containers:
      - name: realtime-demo-app
        image: asampavan14322/realtime-demo-app:latest
        ports:
        - containerPort: 3000